sonar.projectKey=Markoni23_go-project-244
sonar.organization=markoni23

sonar.go.coverage.reportPaths=coverage.out

# Path to source files (excluding test files)
sonar.sources=.
sonar.exclusions=**/*_test.go, cmd/gendiff/**, testdata/**

# Path to test files
sonar.tests=.
sonar.test.inclusions=**/*_test.go

# Go project specific settings
sonar.language=go